### ISSUE TITLE
Conditional formatting problem with ref to other sheet

### ISSUE THREAD

**Issue by jmorecru** [jxlsteam/jxls#72] opened 2020-11-03 08:45 UTC
I have created same conditional formatting rules in the template sheet with a multisheet comment. It does not copy this rules when creating the new sheets. I attach examples files.

Version is 2.8.1

```
<dependency>
  <groupId>org.jxls</groupId>
  <artifactId>jxls</artifactId>
  <version>2.8.1</version>
</dependency>
    <dependency>
        <groupId>org.jxls</groupId>
        <artifactId>jxls-poi</artifactId>
        <version>2.8.1</version>
</dependency>
```

**Comment by jmorecru** [comment] 2020-11-03 08:47
[IssueJxls.zip](https://github.com/jxlsteam/jxls/files/5480110/IssueJxls.zip)

**Comment by jmorecru** [comment] 2020-11-03 12:42
Same result with version 2.9

**Comment by jmorecru** [comment] 2020-11-03 13:20
It fails if the condition has reference to other sheet in the workbook. For example:
=IGUAL(FECHA(2021;8;1);'Fechas Solicitudes'!$A$4)

**Comment by SoltauFintel** [comment] 2020-11-03 13:41
Because of Corona, we are currently spending significantly less time on JXLS. Therefore an answer or processing can take longer.

**Comment by edu-de** [comment] 2021-04-24 18:45
Hi @jmorecru 

I would recommend you to delete everything unnecessary from the template, so you have a minimal example template where the issue occurs. With a minimal example it would be much easier to reproduce and maybe correct the problem.

**Comment by edu-de** [comment] 2021-04-25 10:45
Hi @jmorecru

I created a minimal example (attached) and I confirm see the issue also in jxls 2.10.0 too

[issue72.xlsx](https://github.com/jxlsteam/jxls/files/6371757/issue72.xlsx)
[issue72_output.xlsx](https://github.com/jxlsteam/jxls/files/6371756/issue72_output.xlsx)

**Comment by edu-de** [comment] 2021-04-25 12:18
Hi @jmorecru 

this seems to be a bug in POI 4.1.2, not in JXLS. 

JXLS uses this:
org.jxls.transform.poi.PoiSheetData.createSheetData(Sheet, PoiTransformer)

`SheetConditionalFormatting sheetConditionalFormatting = sheet.getSheetConditionalFormatting();
        for (int i = 0; i < sheetConditionalFormatting.getNumConditionalFormattings(); i++) {
...
}
`

which relies on POI's sheet.getSheetConditionalFormatting(). 

Here you see a simple POI program which shows the number of conditional formattings:

`
import java.io.File;

import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFSheet;

public class ReadPoi {

   public static final String XLSX_FILE_PATH = "/path/to/your/EXCEL.MESES.xlsx";

   public static void main(String[] args) throws Exception {
      Workbook workbook = WorkbookFactory.create(new File(XLSX_FILE_PATH));

      for (Sheet sheet : workbook) {
         XSSFSheet xsheet = (XSSFSheet) sheet;
         System.out.println(sheet.getSheetName() + " has "
               + xsheet.getSheetConditionalFormatting().getNumConditionalFormattings() + " conditional formattings");
      }
   }
}
`

the output is:
Cabecera has 0 conditional formattings
Indisponibilidades has 0 conditional formattings
Fechas Solicitudes has 0 conditional formattings
Fechas Solicitudes Comer has 0 conditional formattings
Template has 0 conditional formattings

so POI doesn't see your conditional formattings.

I can confirm this too with the issue72.xlsx, I get this output:
Tabelle1 has 0 conditional formattings
MyData has 0 conditional formattings

I modified issue72.xlsx to issue72_ok.xlsx. Here, the conditional formatting references a cell *in the same sheet* (attached).
The output I get for this is:
Tabelle1 has 1 conditional formattings
MyData has 0 conditional formattings

which confirms that POI seems to not see conditional formattings *referencing another sheet*.

I think there is no jxls bug here.

[issue72_ok.xlsx](https://github.com/jxlsteam/jxls/files/6371895/issue72_ok.xlsx)

**Comment by edu-de** [comment] 2021-04-25 12:45
I just tested, same behavior with POI 5.0.0

**Comment by edu-de** [comment] 2021-04-25 13:05
https://lists.apache.org/thread.html/rd0a7c7265b100109b28a9d8720b09ca45d93ddc11477d53fea7247ea%40%3Cdev.poi.apache.org%3E

**Comment by SoltauFintel** [comment] 2021-04-26 06:22
So we can close this ticket with 'not a bug'?

**Comment by edu-de** [comment] 2021-04-26 07:38
yes, I think so

**Comment by edu-de** [comment] 2021-04-26 08:22
I opened a bug here: 
https://bz.apache.org/bugzilla/show_bug.cgi?id=65266

**Comment by jmorecru** [comment] 2021-04-26 08:52
Thank you both!!!

**Closed** 2021-04-28 10:44 UTC
Labels: bug
