### ISSUE TITLE
Issue in Excel Output while using SXSSF Transformer with JXLS (>=2.7.0)

### ISSUE THREAD

**Issue by vaibhavk311** [jxlsteam/jxls#153] opened 2021-12-14 16:41 UTC
Hey Team,

I've observed that the static cells are getting erased in output when I'm using SXSSF transformer to transform and apply the area as per the comments from template.

I'm using JXLS 2.11.0 and JXLS-POI 2.11.0.

Moreover I've noted that such behavior is observed in versions newer that JXLS 2.7.0 with SXSSF Transformer

This behavior exists with fixed set of pattern i.e. in which static cell is either to left or right of iterated cell.

[Sample Template](https://i.stack.imgur.com/pjoBZ.png)

Output : [JXLS 2.11.0 Output](https://i.stack.imgur.com/uZpIR.png)

Note that A3 cell("Manager") from Template is erased.

Any comments/lead/resolution if bug would be highly appreciated

**Comment by vaibhavk311** [comment] 2021-12-15 08:19
@SoltauFintel Any updates please

**Comment by SoltauFintel** [comment] 2021-12-15 10:17
in general: You can not use Streaming for everything. Usually it's used for 1 simple data list on 1 sheet.

So it works with 2.7.0 and does not work with 2.11.0 ? (Maybe caused by PR #70 ..?)

**Comment by vaibhavk311** [comment] 2021-12-15 10:28
@SoltauFintel It works fine for JXLS 2.6.x version but it is breaking for versions greater that (>=2.7.0).
Can you help us out here in case we want to preserve the same functionality offered in 2.7.x but for 2.11.0 JXLS-Version ?

**Comment by SoltauFintel** [comment] 2021-12-15 13:23
If you want to speed things up you can push a PR containing a (failin') testcasse. Or maybe in the 2nd step search for the bug.

**Comment by SoltauFintel** [comment] 2021-12-16 08:27
I cannot reproduce this. In my opinion you cannot use streaming for this template.

We need a testcase; pushed as PR. Please create the template from scratch using only Microsoft Excel.

**Comment by vaibhavk311** [comment] 2021-12-17 05:02
@SoltauFintel   
Can you please give me the access to Push the PR(Code) to a remote branch. 
My githubId is vaibhavk311
Currently it says that : 
remote: Permission to jxlsteam/jxls.git denied to vaibhavk311.
fatal: unable to access 'https://github.com/jxlsteam/jxls.git/': The requested URL returned error: 403

**Comment by SoltauFintel** [comment] 2021-12-17 05:13
@vaibhavk311 
You must fork this repo. see https://github.com/jxlsteam/jxls/blob/master/CONTRIBUTING.md

**Comment by vaibhavk311** [comment] 2021-12-17 05:35
Sure thanks @SoltauFintel 
PR : https://github.com/jxlsteam/jxls/pull/155

**Comment by SoltauFintel** [comment] 2021-12-17 05:55
@vaibhavk311 
Did you recreate the template from scratch using MS Excel? Sometimes templates are just broken.

**Comment by vaibhavk311** [comment] 2021-12-17 05:58
@SoltauFintel yes i recreated it from scratch

**Comment by SoltauFintel** [comment] 2021-12-17 07:57
Analysis

- cause is not PR #70
- cause is not POI 4.1.0 (same error with 4.0.1)

**Comment by vaibhavk311** [comment] 2021-12-17 08:30
@SoltauFintel Thanks for RCA :)
What is the resolution to be made

**Comment by SoltauFintel** [comment] 2021-12-17 08:32
What means RCA?

**Comment by SoltauFintel** [comment] 2021-12-17 08:35
@vaibhavk311
Let's wait for leonate.
You could try to set transformer.forwardOnly to true.

**Comment by vaibhavk311** [comment] 2021-12-17 08:41
@SoltauFintel 
RCA-> Root Cause Analysis 
Sure i'll try doing this but transformer.forwardOnly will not support streaming right ?

**Comment by leonate** [comment] 2021-12-17 12:26
AFAIR `isForwardOnly` property was introduced to differentiate between streaming and not streaming transformers
`   public boolean isForwardOnly() {
        return isStreaming();
    }`

With a streaming transformer (SXSSF) we cannot rewrite already written cells. 
But I suppose some regression was introduced with the change.

**Comment by vaibhavk311** [comment] 2021-12-20 04:18
@leonate 
Thanks for the response :) 
What is the resolution to be made

**Comment by ankurkumarHL** [comment] 2021-12-22 10:43
@vaibhavk311 I am facing same issue in, did you get the solution?

**Comment by ankurkumarHL** [comment] 2021-12-22 10:46
@leonate when can we expect this regression to be fixed?

**Comment by SoltauFintel** [comment] 2021-12-22 14:18
There's no solution yet. See comment in PR 156. JXLS is no full-time project. It's done when it's done. :-) And there is no release date yet.

**Comment by leonate** [comment] 2021-12-27 13:33
The issue fixed in pull request #159

**Closed by leonate** 2021-12-27 13:33 UTC
Labels: bug

**Comment by vaibhavk311** [comment] 2021-12-28 04:39
Thanks @leonate , @SoltauFintel  :)
Just one Quick Question : 
Will it be released in JXLS - 2.12.0 Version ?

**Comment by leonate** [comment] 2021-12-28 08:31
> Will it be released in JXLS - 2.12.0 Version ?

That's the plan.

**Comment by SoltauFintel** [comment] 2022-03-07 10:15
This change causes error #173
